//
//  DocInfo.swift
//  DocSpellFramework
//
//  Copyright (c) 2020 Anodized Software, Inc.
//
//  Permission is hereby granted, free of charge, to any person obtaining a
//  copy of this software and associated documentation files (the "Software"),
//  to deal in the Software without restriction, including without limitation
//  the rights to use, copy, modify, merge, publish, distribute, sublicense,
//  and/or sell copies of the Software, and to permit persons to whom the
//  Software is furnished to do so, subject to the following conditions:
//
//  The above copyright notice and this permission notice shall be included in
//  all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//  DEALINGS IN THE SOFTWARE.
//

import Foundation
import SourceKittenFramework

/// The `SwiftDocs` type returned by `SourceKittenFramework` contains documentation information represented by a
/// dictionary. This struct simplifies accessing values in one of these dictionaries. It also allows for recursively
/// searching through one to find documentation.
struct DocInfo {

    /// The raw dictionary generated by `SourceKit` via `SourceKittenFramework`.
    private var dictionary: [String: SourceKitRepresentable]

    init(dictionary: [String: SourceKitRepresentable]) {
        self.dictionary = dictionary
    }

    /// The children of this instance.
    private var substructure: [DocInfo]? {
        let d = dictionary["key.substructure"] as? [[String: SourceKitRepresentable]]
        return d?.map { DocInfo(dictionary: $0)}
    }

    /// Processed doc comment. This is only used when recursively searching for child instances.
    private var docComment: String? {
        return dictionary["key.doc.comment"] as? String
    }

    /// The source doc comment begins at this byte offset in the source file.
    var docOffset: ByteCount? {
        return (dictionary["key.docoffset"] as? Int64).map(ByteCount.init)
    }

    /// The source doc comment length in bytes.
    var docLength: ByteCount? {
        return (dictionary["key.doclength"] as? Int64).map(ByteCount.init)
    }

    /// The byte range of the source doc comment in the source file.
    var docCommentByteRange: ByteRange? {
        guard let location = docOffset, let length = docLength else {
            return nil
        }

        return ByteRange(location: location, length: length)
    }

    /// Recursively searches this instance and its children (via the `substructure` property) to find instances that
    /// represent a doc comment (i.e., where `docComment` is not `nil`).
    func findDocumentationRecursively() -> [DocInfo] {
        let base: [DocInfo] =
            docComment != nil
                ? [self]
                : []

        return base + (substructure?.flatMap({ $0.findDocumentationRecursively() }) ?? [])
    }
}
